#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# 校验 git commit message 格式
# build
# ci - 集成流程修改
# docs
# feat
# fix
# perf - 性能优化
# refactor - 重构代码(既没有新增功能，也没有修复 bug)
# revert - 回滚某个更早之前的提交
# style - 不影响程序逻辑的代码修改(修改空白字符，补全缺失的分号等)
# test
# chore - 不属于以上类型的其他类型(日常事务)
npx --no-install commitlint --edit $1